deviceplugin: new sockets for each test
Reusing the same socket for grpc calls in tests can lead to transient
failures when attempting calls on an unlinking socket (no such file).

```
grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /tmp/mock.sock: connect: no such file or directory"; Reconnecting to {/tmp/mock.sock <nil>}
E0925 11:58:41.469339     589 endpoint.go:89] listAndWatch ended unexpectedly for device plugin mock with error rpc error: code = Unavailable desc = grpc: the connection is unavailable
--- FAIL: TestList (0.00s)
        Error Trace:    endpoint_test.go:55
        Error:          Received unexpected error:
                        rpc error: code = Unavailable desc = grpc: the connection is unavailable
```

Instead generate a new name for each test, this seems to remove the odd
random errors in tests.
Additionally we should also check for server availability in tests, but
the current RPC scheme doesnt exactly have a health check endpoint that
is usually used for such purpose (together with grpc.FailFast).

Also makes registraion tests failed within timeout instead of waiting
for the channel forever.